### ISSUE TITLE
Save levels to separate files breaks import

### ISSUE THREAD

**Issue by wy477wh173** [evolutionleo/LDtkParser#7]
Toggling the "Save levels to separate files" setting in LDTK Project Settings appears to break import, and I can't figure out why. It doesn't throw a "Error! Cannot find the matching level" or "Warning! LDtk project file is not specified or file does not exist!" error, it seems to work fine, but loads into a blank room. 

when I download the demo project and run it, it just can't find the files either way (IDE&Runtime v2022.5.0.8) and throws a full "Warning! LDtk project file is not specified or file does not exist! (" + string(file) + " whether "Save levels to separate files" is on or off.

**Comment by evolutionleo** [comment]
sorry multiple project files aren't currently supported :(

**Comment by wy477wh173** [comment]
Good to know, thanks :)
